ENH : Implement a function for computing the DVARS
nipraxis-spring-2022/diagnostics-Lemanics pull request #11
Opened 2022-05-17 15:46 UTC by celprov

2022-05-17 15:50 UTC, effigies approved these changes
Looks good!

2022-05-17 15:57 UTC, hugofluhr requested changes
used np.diff to be more concise

2022-05-17 15:57 UTC, hugofluhr commented on findoutlie/metrics.py
> +    diff = diff[...,1:]
```suggestion
    voxel_per_time = np.reshape(data, (-1, data.shape[-1]))
    diff = np.diff(voxel_per_time)
```

2022-05-17 16:15 UTC, celprov reviewed
This shortcut to compute differences of an array sounds reasonable to me.

2022-05-18 07:22 UTC, hugofluhr approved these changes

2022-05-18 07:22 UTC, merged